import json
import random
from datetime import datetime, timedelta

def generate_mock_data():
    brands = [
        "Binance", "Coinbase", "Kraken", "Bybit", "Bitget", "OKX", "KuCoin", "Huobi", "Gate.io", "Bitfinex",
        "Gemini", "Crypto.com", "eToro", "Ledger", "Trezor", "Metamask", "Trust Wallet", "Exodus", "SafePal", "Tangem",
        "Phemex", "MEXC", "BingX", "BitStamp", "StormGain", "PrimeXBT", "Margex", "Changelly", "Simplex", "MoonPay"
    ]
    
    niches = ["Exchange", "Wallet", "DeFi", "Trading Bot", "Tax Tool", "Education", "Mining", "Staking"]
    
    data = []
    
    for i in range(100):
        brand_base = random.choice(brands)
        niche = random.choice(niches)
        brand_name = f"{brand_base} {niche} {random.randint(1, 99) if random.random() > 0.7 else ''}".strip()
        
        commission_rate = random.randint(10, 50)
        if random.random() > 0.8:
            commission_rate = random.randint(50, 70) # High ticket
            
        traffic = random.randint(50000, 5000000)
        
        item = {
            "id": f"aff_{i+1000}",
            "brand": brand_name,
            "program_url": f"https://www.{brand_name.lower().replace(' ', '')}.com/affiliates",
            "commission_percent": commission_rate,
            "commission_type": random.choice(["Lifetime RevShare", "CPA", "Hybrid", "Recurring"]),
            "traffic_3m": traffic,
            "legitimacy_score": round(random.uniform(7.5, 9.9), 1),
            "cookie_duration": random.choice([30, 60, 90, 120, "Lifetime"]),
            "payment_methods": random.sample(["USDT", "BTC", "Bank Transfer", "PayPal", "Wise"], k=random.randint(1, 3)),
            "category": niche,
            "network": random.choice(["In-house", "Impact", "CJ", "ShareASale", "PartnerStack"]),
            "status": "Active"
        }
        data.append(item)
        
    # Write to JS file
    js_content = f"""/**
 * Mock Data: Crypto Affiliate Programs
 * Generated by Python Script
 */
export const mockCryptoAffiliates = {json.dumps(data, indent=4)};
"""
    
    with open('/Users/thomas/adecos-mvp/frontend/src/data/mockCryptoAffiliates.js', 'w') as f:
        f.write(js_content)
    
    print("Successfully generated 100 mock items.")

if __name__ == "__main__":
    generate_mock_data()
